{{ if .Values.amf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: amf-free5gc-sctp
  labels:
    epc-mode: amf
spec:
  type: NodePort
  selector:
    epc-mode: amf
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
      nodePort: 30412
---
apiVersion: v1
kind: Service
metadata:
  name: free5gc-amf
  annotations:
    skupper.io/proxy: http2
    skupper.io/address: {{ .Values.amf.serviceName }}
  labels:
    epc-mode: amf
spec:
  type: NodePort
  selector:
    epc-mode: amf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-amf-d
  labels:
    epc-mode: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      labels:
        epc-mode: amf
    spec:    
      containers:
        - name: amf
          image: "{{ .Values.amf.image }}"
          ports:
            - containerPort: {{ .Values.amf.port }}
              protocol: TCP
            - containerPort: 38412
              name: amf-sctp
              protocol: SCTP
          env:
            - name: GIN_MODE
              value: debug
          securityContext:
            privileged: true
            capabilities:
              add:
              - NET_ADMIN
          command:
            - /free5gc/amf
          volumeMounts:
            - name: conf
              mountPath: /free5gc/config/amfcfg.yaml
              subPath: amfcfg.yaml
      volumes:
        - name: conf
          configMap:
            name: amf-config
            items:
            - key: amfcfg.yaml
              path: amfcfg.yaml
{{ end }}
