{{ if .Values.udm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: free5gc-udm
  annotations:
    skupper.io/proxy: http2
    skupper.io/address:  {{ .Values.udm.serviceName }}
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
    - protocol: TCP
      port:  {{ .Values.udm.port }}
      targetPort:  {{ .Values.udm.port }}
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: free5gc-udm-d
  labels:
    epc-mode: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      labels:
        epc-mode: udm
    spec:  
      {{ .Values.udm.custom }}
      containers:
        - name: udm
          image: "{{ .Values.udm.image }}"
          command:
            - /free5gc/udm
          env:
            - name: GIN_MODE
              value: release
          ports:
            - containerPort: {{ .Values.udm.port }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: conf
              mountPath: /free5gc/config/udmcfg.yaml
              subPath: udmcfg.yaml
      volumes:
        - name: conf
          configMap:
            name: udm-config
            items:
            - key: udmcfg.yaml
              path: udmcfg.yaml
{{ end }}