apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: distributed-free5gc
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: 5g-core-clusters
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'distributed-free5gc-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'TBD: Make distributed-free5gc a repo'
        targetRevision: main
        path: '5gcore'
        helm: 
          valueFiles:
            - '{{name}}-values.yaml'
      destination:
        server: '{{server}}'
        namespace: open5gcore
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
