---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: free5gc-skupper-resources
  namespace: free5gc
spec:
  pathname: free5gc
  type: Namespace
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: free5gc-skupper-sub
  namespace: free5gc
spec:
  channel: free5gc/free5gc-skupper-resources
  placement:
    placementRef:
      kind: PlacementRule
      name: free5gc-skupper-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: free5gc-skupper-placement
  namespace: free5gc
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      5g-core: "True"
---
apiVersion: v1
kind: Secret
metadata:
  name: link-to-central
  namespace: free5gc
  annotations:
    apps.open-cluster-management.io/deployables: "true"
  labels:
    skupper.io/type: connection-token-request